name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload site folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'  # this is your folder!

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4